version: '3'

services:
  auth:
    build: ./
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - CONFIG=./config/config.json
  db:
    container_name: db
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: some_user
      POSTGRES_PASSWORD: some_password
      POSTGRES_DB: auth
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /home/$USER/authServiceDb:/var/lib/postgresql/data/pgdata