version: '3'


services:
  auth:
    build: ./
    ports:
      - "8080:8080"
      - "8000-8050:8080"
    depends_on:
      - db
  db:
    container_name: db
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: some_user
      POSTGRES_PASSWORD: some_password
      POSTGRES_DB: auth
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /home/$USER/authServiceDb:/var/lib/postgresql/data/pgdata