version: '3'


services:
  auth:
    build: ./
    restart: untill-stopped
    ports:
      -"8080:8080"
      -"8000-8050:8080"
    depends_on:
      - db
  db:
    container_name: db
    image: postgres
    restart: untill-stopped
    environment:
      POSTGRES_USER: some_user
      POSTGRES_PASSWORD: some_password
      POSTGRES_DB: users
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /home/$USER/users:/var/lib/postgresql/data/pgdata